Create a 3×3×3 array with random value

In [ ]:
 import numpy as np
x = np.random.random((3,3,3))
print(x)

Create 5×5 matrix with values 1,2,3,4 just below digonal

In [ ]:
 import numpy as np
x = np.diag([1, 2, 3, 4])
print(x)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


Create 8×8 matrix and fill it with checker board pattern

In [ ]:
 import numpy as np
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Normalise 5×5 random matrix

In [ ]:
 import numpy as np
x= np.random.random((5,5))
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

How to find comman value between two arrays

In [ ]:
 import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


How to get dates of yesterday today and tomorrow

In [ ]:
 import datetime 
today = datetime.date.today()
yesterday = today - datetime.timedelta(days = 1)
tomorrow = today + datetime.timedelta(days = 1) 
print('Yesterday : ',yesterday)
print('Today : ',today)
print('Tomorrow : ',tomorrow)

Yesterday :  2020-07-30
Today :  2020-07-31
Tomorrow :  2020-08-01


Consider two random arrays and check if they are equal

In [ ]:
 
an_array = np.array([[1,2],[3,4]])
another_array = np.array([[1,2],[3,4]])
 
comparison = an_array == another_array
equal_arrays = comparison.all()
 
print(equal_arrays)

True


Create random vector of size 10 and replace the maximum value by 0

In [1]:
 import numpy as np
x = np.random.random(10)
 
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)

Original array:
[0.25720882 0.1218768  0.41458052 0.84984351 0.48085655 0.70905488
 0.93135214 0.003253   0.90605817 0.41060575]
Maximum value replaced by 0:
[0.25720882 0.1218768  0.41458052 0.84984351 0.48085655 0.70905488
 0.         0.003253   0.90605817 0.41060575]


How to print all value of an array

In [5]:
 
my_array = np.arange(10)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


Substract the mean of each row of matrix

In [8]:
 
X = np.random.rand(5, 5)
 
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[ 0.18607022  0.28148372  0.155358   -0.57637857 -0.04653338]
 [ 0.06691784  0.3619212  -0.09666304  0.00291372 -0.33508972]
 [-0.21102731  0.04092366  0.17435398 -0.2594224   0.25517208]
 [ 0.26134867  0.06614589  0.46238135 -0.41723308 -0.37264284]
 [ 0.24205486 -0.44743799 -0.36294634  0.21504589  0.35328358]]


 Consider a vector,how to add 1 to each element indexed by a 2nd vector

In [22]:
 Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[2. 3. 5. 3. 3. 1. 3. 3. 2. 5.]


How to get digonal of dot product

In [21]:
 a = np.arange(4).reshape(2,2)
 
a.diagonal()
a.diagonal(1)

array([1])

 How to find the most frequent value in an array

In [14]:
 x = np.random.randint(0, 10, 40)
print(x)
print(np.bincount(x).argmax())

[2 6 9 3 7 7 5 0 6 7 8 0 4 1 0 6 8 7 2 9 3 7 4 4 2 2 5 6 2 9 2 0 1 8 9 9 5
 8 3 6]
2


How to get the n largest values of an array

In [12]:
 x = np.arange(7)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

[6]


How to create a record array from regular array

In [11]:
 a1=np.array([1,2,3,4])
a2=np.array(['knp','belll','green','numpy'])
a3=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([a1, a2, a3],names='a,b,c')
print(result[0])
print(result[1])
print(result[2])

(1, 'knp', 12.2)
(2, 'belll', 15.)
(3, 'green', 20.)
